# openapi.yaml
openapi: 3.0.4
info:
  version: 1.0.0
  title: Test API
  description: A test API
paths:
  /healthcheck/readiness:
    get:
      tags:
        - healthcheck
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
        '503':
          description: 'Service Unavailable'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
  /healthcheck/liveness:
    get:
      tags:
        - healthcheck
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
  /api/v1/transfers:
    post:
      summary: Create a transfer
      tags:
        - transfers
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Transfer'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'

components:
  schemas:
    Healthcheck:
      type: object
      properties:
        status:
          type: string
          example: 'OK'
        dependencies:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: 'postgresql'
              status:
                type: string
                example: 'OK'
    Transfer:
      type: object
      properties:
        user_id:
          type: string
          example: 'u-515ffa15-43af-4773-b0d5-e80a53613a4b'
        amount: 
          type: number
          format: double
          example: 1000
        currency: 
          type: string
          example: 'IDR'
        notes: 
          type: string
          example: 'Payment for goods purchased'
        reference_id: 
          type: string
          example: 'ORD123456789'
        metadata: 
          type: object
          properties: 
            name: 
              type: string
              example: 'Jane Smith'
            email: 
              type: string
              example: 'jane.smith@example.com'
            bank_account: 
              type: object
              properties: 
                account_number: 
                  type: string
                  example: '9876543210'
                bank_name: 
                  type: string
                  example: 'Another Bank'
                bank_code: 
                  type: string
                  example: '123456789'
